"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-02 15:03:21.322419
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("portfolio_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_accounts_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "configuration_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("trading_enabled", sa.Boolean(), nullable=False),
        sa.Column("live_confirmed", sa.Boolean(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("configuration_changes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_configuration_changes_config_hash"), ["config_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_configuration_changes_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("decision_id", sa.String(length=48), nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=True),
        sa.Column("correlation_id", sa.String(length=48), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("signal_action", sa.String(length=8), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("position_size", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_client_order_id"), ["client_order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_decision_id"), ["decision_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_decisions_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("tradable", sa.Boolean(), nullable=False),
        sa.Column("leveraged", sa.Boolean(), nullable=False),
        sa.Column("derivative", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "kv_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("volume", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "timestamp", "timeframe", name="uq_market_data_bar"),
    )
    with op.batch_alter_table("market_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_data_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_data_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=48), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("time_in_force", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("avg_fill_price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("commission", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("risk_checks", sa.JSON(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_broker_order_id"), ["broker_order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_client_order_id"), ["client_order_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_orders_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_idempotency_key"), ["idempotency_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_symbol"), ["symbol"], unique=False)
        batch_op.create_index("ix_orders_symbol_status", ["symbol", "status"], unique=False)

    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reserved_cash", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("invested_capital", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("portfolio_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("buying_power", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("exposure", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("daily_pnl", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("total_pnl", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("drawdown", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("peak_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("n_positions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_portfolio_snapshots_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "risk_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=48), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=True),
        sa.Column("client_order_id", sa.String(length=48), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_events_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("strength", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signals_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "strategy_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("correlation_id", sa.String(length=48), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("symbols_evaluated", sa.Integer(), nullable=False),
        sa.Column("signals_generated", sa.Integer(), nullable=False),
        sa.Column("orders_submitted", sa.Integer(), nullable=False),
        sa.Column("orders_vetoed", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("strategy_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategy_runs_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_runs_run_id"), ["run_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_strategy_runs_started_at"), ["started_at"], unique=False)

    op.create_table(
        "system_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=48), nullable=False),
        sa.Column("component", sa.String(length=48), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_events_component"), ["component"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_correlation_id"), ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fill_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=48), nullable=False),
        sa.Column("broker_fill_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("commission", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_order_id"],
            ["orders.client_order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fills_client_order_id"), ["client_order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fills_fill_id"), ["fill_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_fills_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_fills_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["portfolio_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_snapshot_id"), ["snapshot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_positions_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_positions_timestamp"), ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_timestamp"))
        batch_op.drop_index(batch_op.f("ix_positions_symbol"))
        batch_op.drop_index(batch_op.f("ix_positions_snapshot_id"))

    op.drop_table("positions")
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fills_timestamp"))
        batch_op.drop_index(batch_op.f("ix_fills_symbol"))
        batch_op.drop_index(batch_op.f("ix_fills_fill_id"))
        batch_op.drop_index(batch_op.f("ix_fills_client_order_id"))

    op.drop_table("fills")
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_system_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_system_events_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_system_events_component"))

    op.drop_table("system_events")
    with op.batch_alter_table("strategy_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_strategy_runs_run_id"))
        batch_op.drop_index(batch_op.f("ix_strategy_runs_correlation_id"))

    op.drop_table("strategy_runs")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signals_timestamp"))
        batch_op.drop_index(batch_op.f("ix_signals_symbol"))
        batch_op.drop_index(batch_op.f("ix_signals_run_id"))

    op.drop_table("signals")
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_risk_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_risk_events_correlation_id"))

    op.drop_table("risk_events")
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_snapshots_timestamp"))

    op.drop_table("portfolio_snapshots")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_symbol_status")
        batch_op.drop_index(batch_op.f("ix_orders_symbol"))
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_orders_created_at"))
        batch_op.drop_index(batch_op.f("ix_orders_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_orders_client_order_id"))
        batch_op.drop_index(batch_op.f("ix_orders_broker_order_id"))

    op.drop_table("orders")
    with op.batch_alter_table("market_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_data_timestamp"))
        batch_op.drop_index(batch_op.f("ix_market_data_symbol"))

    op.drop_table("market_data")
    op.drop_table("kv_state")
    op.drop_table("instruments")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_timestamp"))
        batch_op.drop_index(batch_op.f("ix_decisions_symbol"))
        batch_op.drop_index(batch_op.f("ix_decisions_run_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_decision_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_client_order_id"))

    op.drop_table("decisions")
    with op.batch_alter_table("configuration_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_changes_timestamp"))
        batch_op.drop_index(batch_op.f("ix_configuration_changes_config_hash"))

    op.drop_table("configuration_changes")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_timestamp"))
        batch_op.drop_index(batch_op.f("ix_accounts_account_id"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
